version: '3.8'

services:
  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - data:/data
    networks:
      - redis-network
    restart: always

networks:
  redis-network:
    driver: bridge

volumes:
  data:
