version: '3.8'

services:
  elasticsearch:
    container_name: elsticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - data:/data
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"

volumes:
  data:
