version: '3.8'

services:
  neo4j:
    image: neo4j:5.11.0
    container_name: neo4j
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - data:/data
      - plugins:/plugins
    restart: unless-stopped

volumes:
  data:
  plugins:
