version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=none  # auth forbidden
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/var/lib/neo4j
    restart: unless-stopped

volumes:
  neo4j-data:
